### ISSUE TITLE
Does not work on MINGW 

### ISSUE THREAD

**Issue by astroanu** [anseki/gulp-confirm#1]
i'm using this in a gulp task, it work on the windows powershell but skips on git bash for windows. No errors displayed. I guess the confirm method is not triggered at all.

gulp-run 1.7.1
windows 10
git bash v 2.12.0.1

**Comment by anseki** [comment]
Hi @astroanu, thank you for the comment.

Since gulp-confirm has a conversation with the user via TTY, of course it can't work in an environment without TTY, other programs that use TTY too. For example, REPL also may not work. try this:

```
node
console.log('foo');
```

You should use it in an environment that TTY is available. Also, you'd better not use MinGW for others because it has other problems as everyone knows.
I think that you probably use a decent terminal such as [Cmder](http://cmder.net/) instead of CMD that has many problems.

Or, if you really want to use MinGW, https://github.com/anseki/readline-sync/issues/33 might help you. But I don't recommend it.

```js
process.stdin.isTTY = process.stdout.isTTY = true;
```
